//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionPRJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FulcurmEmployee
    {
        public int FulcurmEmployeeId { get; set; }
        public string FulcurmEmployeeName { get; set; }
        public string FulcurmEmployeeEmail { get; set; }
        public Nullable<System.DateTime> FulcurmEmployeeLastReport { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
