//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionPRJ.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OilDataCollectionEntities : DbContext
    {
        public OilDataCollectionEntities()
            : base("name=OilDataCollectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<FulcurmEmployee> FulcurmEmployees { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemInformation> SystemInformations { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<WebUser> WebUsers { get; set; }
        public virtual DbSet<Well> Wells { get; set; }
        public virtual DbSet<WellType> WellTypes { get; set; }
    
        public virtual ObjectResult<SpSelect_WellData_Result> SpSelect_WellData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpSelect_WellData_Result>("SpSelect_WellData");
        }
    
        public virtual ObjectResult<SpSelect_dashboardWellmarkers_Result> SpSelect_dashboardWellmarkers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpSelect_dashboardWellmarkers_Result>("SpSelect_dashboardWellmarkers");
        }
    }
}
