//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionPRJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int RolePermissionId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> PermissionId { get; set; }
        public Nullable<int> SystemInformationId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual SystemInformation SystemInformation { get; set; }
    }
}
