//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionPRJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUser
    {
        public int WebUserId { get; set; }
        public string WebUserName { get; set; }
        public string WebEmailId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserPassword { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Location Location { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
