//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionPRJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Well
    {
        public string WellName { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> WellTypeId { get; set; }
        public Nullable<int> Flow { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int WellId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual WellType WellType { get; set; }
    }
}
